version: '3.8'

services:
  mangala-app:
    image: ghcr.io/biteker/mangala-prime:latest
    container_name: mangala-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/db/dev.db
    volumes:
      # SQLite veritabanını bağımsız db klasöründe saklayarak şema maskelenmesini önler
      - ./db:/app/db
    networks:
      - web-network

networks:
  web-network:
    external: true
